//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionClient.Localization
{


    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedStrings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GestionClient.Localization.LocalizedStrings", typeof(LocalizedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à About.
        /// </summary>
        internal static string A_propos_Sub_Menu {
            get {
                return ResourceManager.GetString("A_propos_Sub_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Compatibility: Windows XP SP3 / Windows 7 / ++.
        /// </summary>
        internal static string About_Compatibilité {
            get {
                return ResourceManager.GetString("About_Compatibilité", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copyright © 2014-2015.
        /// </summary>
        internal static string About_Copyright {
            get {
                return ResourceManager.GetString("About_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Developer: AXeL.
        /// </summary>
        internal static string About_Dev {
            get {
                return ResourceManager.GetString("About_Dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .Net version: 2.0.
        /// </summary>
        internal static string About_DotNet_Version {
            get {
                return ResourceManager.GetString("About_DotNet_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Free of rights and use..
        /// </summary>
        internal static string About_End {
            get {
                return ResourceManager.GetString("About_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Version: 1.0.
        /// </summary>
        internal static string About_Version {
            get {
                return ResourceManager.GetString("About_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add.
        /// </summary>
        internal static string Ajouter_Client_Ajouter_Button {
            get {
                return ResourceManager.GetString("Ajouter_Client_Ajouter_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add / Edit.
        /// </summary>
        internal static string Ajouter_Client_Ajouter_Modifier_Photo_Button {
            get {
                return ResourceManager.GetString("Ajouter_Client_Ajouter_Modifier_Photo_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Customer.
        /// </summary>
        internal static string Ajouter_Client_Client_GroupBox {
            get {
                return ResourceManager.GetString("Ajouter_Client_Client_GroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date of Birth :.
        /// </summary>
        internal static string Ajouter_Client_Date_Naissance_Label {
            get {
                return ResourceManager.GetString("Ajouter_Client_Date_Naissance_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à E-mail :.
        /// </summary>
        internal static string Ajouter_Client_Email_Label {
            get {
                return ResourceManager.GetString("Ajouter_Client_Email_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Last name :.
        /// </summary>
        internal static string Ajouter_Client_Nom_Label {
            get {
                return ResourceManager.GetString("Ajouter_Client_Nom_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New.
        /// </summary>
        internal static string Ajouter_Client_Nouveau_Travail_Button {
            get {
                return ResourceManager.GetString("Ajouter_Client_Nouveau_Travail_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Phone number :.
        /// </summary>
        internal static string Ajouter_Client_Numero_Tel_Label {
            get {
                return ResourceManager.GetString("Ajouter_Client_Numero_Tel_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Photo.
        /// </summary>
        internal static string Ajouter_Client_Photo_GroupBox {
            get {
                return ResourceManager.GetString("Ajouter_Client_Photo_GroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ♂ | ♀:.
        /// </summary>
        internal static string Ajouter_Client_Sexe_Label {
            get {
                return ResourceManager.GetString("Ajouter_Client_Sexe_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add.
        /// </summary>
        internal static string Ajouter_Client_Sub_Menu {
            get {
                return ResourceManager.GetString("Ajouter_Client_Sub_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Work :.
        /// </summary>
        internal static string Ajouter_Client_Travail_Label {
            get {
                return ResourceManager.GetString("Ajouter_Client_Travail_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add customer.
        /// </summary>
        internal static string Ajouter_Client_Win_Name {
            get {
                return ResourceManager.GetString("Ajouter_Client_Win_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Work.
        /// </summary>
        internal static string Ajouter_Travail_1st_GroupBox {
            get {
                return ResourceManager.GetString("Ajouter_Travail_1st_GroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description:.
        /// </summary>
        internal static string Ajouter_Travail_1st_Label {
            get {
                return ResourceManager.GetString("Ajouter_Travail_1st_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add.
        /// </summary>
        internal static string Ajouter_Travail_Ajouter_Button {
            get {
                return ResourceManager.GetString("Ajouter_Travail_Ajouter_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add.
        /// </summary>
        internal static string Ajouter_Travail_Sub_Menu {
            get {
                return ResourceManager.GetString("Ajouter_Travail_Sub_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add a job.
        /// </summary>
        internal static string Ajouter_Travail_Win_Name {
            get {
                return ResourceManager.GetString("Ajouter_Travail_Win_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Client management.
        /// </summary>
        internal static string App_Name {
            get {
                return ResourceManager.GetString("App_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Application.
        /// </summary>
        internal static string Application_Menu {
            get {
                return ResourceManager.GetString("Application_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Arab.
        /// </summary>
        internal static string Arabe_Sub_Menu {
            get {
                return ResourceManager.GetString("Arabe_Sub_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Customer.
        /// </summary>
        internal static string Client_Menu {
            get {
                return ResourceManager.GetString("Client_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connection to the database.
        /// </summary>
        internal static string Connexion_DB_Sub_Menu {
            get {
                return ResourceManager.GetString("Connexion_DB_Sub_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Database connection error!.
        /// </summary>
        internal static string Connexion_To_DB_Error {
            get {
                return ResourceManager.GetString("Connexion_To_DB_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Database connection established..
        /// </summary>
        internal static string Connexion_To_DB_Success {
            get {
                return ResourceManager.GetString("Connexion_To_DB_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à French.
        /// </summary>
        internal static string Français_Sub_Menu {
            get {
                return ResourceManager.GetString("Français_Sub_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tongue.
        /// </summary>
        internal static string Langue_Sub_Menu {
            get {
                return ResourceManager.GetString("Langue_Sub_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Refresh.
        /// </summary>
        internal static string Liste_Client_Actualiser_Button {
            get {
                return ResourceManager.GetString("Liste_Client_Actualiser_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Age.
        /// </summary>
        internal static string Liste_Client_DataGridView_Column_Age {
            get {
                return ResourceManager.GetString("Liste_Client_DataGridView_Column_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à years.
        /// </summary>
        internal static string Liste_Client_DataGridView_Column_Age_Devise {
            get {
                return ResourceManager.GetString("Liste_Client_DataGridView_Column_Age_Devise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Played on.
        /// </summary>
        internal static string Liste_Client_DataGridView_Column_Ajouté_Le {
            get {
                return ResourceManager.GetString("Liste_Client_DataGridView_Column_Ajouté_Le", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date of Birth.
        /// </summary>
        internal static string Liste_Client_DataGridView_Column_Date_Naissance {
            get {
                return ResourceManager.GetString("Liste_Client_DataGridView_Column_Date_Naissance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à E-mail.
        /// </summary>
        internal static string Liste_Client_DataGridView_Column_Email {
            get {
                return ResourceManager.GetString("Liste_Client_DataGridView_Column_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Payroll amount.
        /// </summary>
        internal static string Liste_Client_DataGridView_Column_Montant_Payé {
            get {
                return ResourceManager.GetString("Liste_Client_DataGridView_Column_Montant_Payé", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dh.
        /// </summary>
        internal static string Liste_Client_DataGridView_Column_Montant_Payé_Devise {
            get {
                return ResourceManager.GetString("Liste_Client_DataGridView_Column_Montant_Payé_Devise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Last name.
        /// </summary>
        internal static string Liste_Client_DataGridView_Column_Nom {
            get {
                return ResourceManager.GetString("Liste_Client_DataGridView_Column_Nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Phone number.
        /// </summary>
        internal static string Liste_Client_DataGridView_Column_Numero_Tel {
            get {
                return ResourceManager.GetString("Liste_Client_DataGridView_Column_Numero_Tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sex.
        /// </summary>
        internal static string Liste_Client_DataGridView_Column_Sexe {
            get {
                return ResourceManager.GetString("Liste_Client_DataGridView_Column_Sexe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Work.
        /// </summary>
        internal static string Liste_Client_DataGridView_Column_Travail {
            get {
                return ResourceManager.GetString("Liste_Client_DataGridView_Column_Travail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Filter by job too.
        /// </summary>
        internal static string Liste_Client_Filtrer_CheckBox {
            get {
                return ResourceManager.GetString("Liste_Client_Filtrer_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Filter clients.
        /// </summary>
        internal static string Liste_Client_Filtrer_GroupBox {
            get {
                return ResourceManager.GetString("Liste_Client_Filtrer_GroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à To print.
        /// </summary>
        internal static string Liste_Client_Imprimer_Button {
            get {
                return ResourceManager.GetString("Liste_Client_Imprimer_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à List of clients.
        /// </summary>
        internal static string Liste_Client_Liste_GroupBox {
            get {
                return ResourceManager.GetString("Liste_Client_Liste_GroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Listing.
        /// </summary>
        internal static string Liste_Client_Sub_Menu {
            get {
                return ResourceManager.GetString("Liste_Client_Sub_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à List of clients.
        /// </summary>
        internal static string Liste_Client_Win_Name {
            get {
                return ResourceManager.GetString("Liste_Client_Win_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à There are no clients! Please add at least 1..
        /// </summary>
        internal static string MessageBox_Aucun_Client {
            get {
                return ResourceManager.GetString("MessageBox_Aucun_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à There are no parts to delete!.
        /// </summary>
        internal static string MessageBox_Aucune_Piece {
            get {
                return ResourceManager.GetString("MessageBox_Aucune_Piece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Customer added!.
        /// </summary>
        internal static string MessageBox_Client_Ajouté {
            get {
                return ResourceManager.GetString("MessageBox_Client_Ajouté", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Customer changed!.
        /// </summary>
        internal static string MessageBox_Client_Modifié {
            get {
                return ResourceManager.GetString("MessageBox_Client_Modifié", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No customer with this name found!.
        /// </summary>
        internal static string MessageBox_Client_Non_trouvé {
            get {
                return ResourceManager.GetString("MessageBox_Client_Non_trouvé", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This client does not have a photo!.
        /// </summary>
        internal static string MessageBox_Client_Sans_Photo {
            get {
                return ResourceManager.GetString("MessageBox_Client_Sans_Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Customer deleted!.
        /// </summary>
        internal static string MessageBox_Client_Supprimé {
            get {
                return ResourceManager.GetString("MessageBox_Client_Supprimé", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Customer deleted! There are no more customers. Closing....
        /// </summary>
        internal static string MessageBox_Client_Supprimé_Plus_Fermeture {
            get {
                return ResourceManager.GetString("MessageBox_Client_Supprimé_Plus_Fermeture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to delete this client?.
        /// </summary>
        internal static string MessageBox_Confirmer_Suppression_Client {
            get {
                return ResourceManager.GetString("MessageBox_Confirmer_Suppression_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to delete this payment?.
        /// </summary>
        internal static string MessageBox_Confirmer_Suppression_Paiement {
            get {
                return ResourceManager.GetString("MessageBox_Confirmer_Suppression_Paiement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to delete this part?.
        /// </summary>
        internal static string MessageBox_Confirmer_Suppression_Piece {
            get {
                return ResourceManager.GetString("MessageBox_Confirmer_Suppression_Piece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to delete this job?.
        /// </summary>
        internal static string MessageBox_Confirmer_Suppression_Travail {
            get {
                return ResourceManager.GetString("MessageBox_Confirmer_Suppression_Travail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Database connection not established!.
        /// </summary>
        internal static string MessageBox_Connexion_Non_Etablie {
            get {
                return ResourceManager.GetString("MessageBox_Connexion_Non_Etablie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Database saved in&gt;.
        /// </summary>
        internal static string MessageBox_DB_Saved_To {
            get {
                return ResourceManager.GetString("MessageBox_DB_Saved_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The description entered already exists!.
        /// </summary>
        internal static string MessageBox_Description_Double {
            get {
                return ResourceManager.GetString("MessageBox_Description_Double", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The job description is mandatory!.
        /// </summary>
        internal static string MessageBox_Description_Obligatoire {
            get {
                return ResourceManager.GetString("MessageBox_Description_Obligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error has occurred !.
        /// </summary>
        internal static string MessageBox_Erreur {
            get {
                return ResourceManager.GetString("MessageBox_Erreur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The payment amount is mandatory!.
        /// </summary>
        internal static string MessageBox_Montant_Obligatoire {
            get {
                return ResourceManager.GetString("MessageBox_Montant_Obligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No.
        /// </summary>
        internal static string MessageBox_NO {
            get {
                return ResourceManager.GetString("MessageBox_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The customer name entered belongs to another customer! Please change it..
        /// </summary>
        internal static string MessageBox_Nom_D_un_Autre_Client {
            get {
                return ResourceManager.GetString("MessageBox_Nom_D_un_Autre_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The customer name entered already exists!.
        /// </summary>
        internal static string MessageBox_Nom_Double {
            get {
                return ResourceManager.GetString("MessageBox_Nom_Double", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Customer&apos;s name is required!.
        /// </summary>
        internal static string MessageBox_Nom_Obligatoire {
            get {
                return ResourceManager.GetString("MessageBox_Nom_Obligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to quit?.
        /// </summary>
        internal static string MessageBox_Quitter {
            get {
                return ResourceManager.GetString("MessageBox_Quitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nothing to delete!.
        /// </summary>
        internal static string MessageBox_Rien_A_Supprimer {
            get {
                return ResourceManager.GetString("MessageBox_Rien_A_Supprimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please select a room!.
        /// </summary>
        internal static string MessageBox_Selectionner_Piece {
            get {
                return ResourceManager.GetString("MessageBox_Selectionner_Piece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Work added!.
        /// </summary>
        internal static string MessageBox_Travail_Ajouté {
            get {
                return ResourceManager.GetString("MessageBox_Travail_Ajouté", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Work deleted!.
        /// </summary>
        internal static string MessageBox_Travail_Supprimé {
            get {
                return ResourceManager.GetString("MessageBox_Travail_Supprimé", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Yes.
        /// </summary>
        internal static string MessageBox_YES {
            get {
                return ResourceManager.GetString("MessageBox_YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add a room.
        /// </summary>
        internal static string Modifier_Client_Ajouter_Piece_ToolTip {
            get {
                return ResourceManager.GetString("Modifier_Client_Ajouter_Piece_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Payment date.
        /// </summary>
        internal static string Modifier_Client_DataGridView_Date_Paiement_Column {
            get {
                return ResourceManager.GetString("Modifier_Client_DataGridView_Date_Paiement_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Payroll amount.
        /// </summary>
        internal static string Modifier_Client_DataGridView_Montant_Column {
            get {
                return ResourceManager.GetString("Modifier_Client_DataGridView_Montant_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DH.
        /// </summary>
        internal static string Modifier_Client_DataGridView_Montant_Column_Devise {
            get {
                return ResourceManager.GetString("Modifier_Client_DataGridView_Montant_Column_Devise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date:.
        /// </summary>
        internal static string Modifier_Client_Date_Paiement_Label {
            get {
                return ResourceManager.GetString("Modifier_Client_Date_Paiement_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Record payment.
        /// </summary>
        internal static string Modifier_Client_Enregistrer_Paiement_Button {
            get {
                return ResourceManager.GetString("Modifier_Client_Enregistrer_Paiement_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit.
        /// </summary>
        internal static string Modifier_Client_Modifier_Button {
            get {
                return ResourceManager.GetString("Modifier_Client_Modifier_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Amount (DH):.
        /// </summary>
        internal static string Modifier_Client_Montant_Label {
            get {
                return ResourceManager.GetString("Modifier_Client_Montant_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New Payment.
        /// </summary>
        internal static string Modifier_Client_Nouveau_Paiement_GroupBox {
            get {
                return ResourceManager.GetString("Modifier_Client_Nouveau_Paiement_GroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Payment.
        /// </summary>
        internal static string Modifier_Client_Paiement_GroupBox {
            get {
                return ResourceManager.GetString("Modifier_Client_Paiement_GroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rooms.
        /// </summary>
        internal static string Modifier_Client_Pieces_GroupBox {
            get {
                return ResourceManager.GetString("Modifier_Client_Pieces_GroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Previous.
        /// </summary>
        internal static string Modifier_Client_Précédent_Button {
            get {
                return ResourceManager.GetString("Modifier_Client_Précédent_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à To research.
        /// </summary>
        internal static string Modifier_Client_Rechercher_Button {
            get {
                return ResourceManager.GetString("Modifier_Client_Rechercher_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à next.
        /// </summary>
        internal static string Modifier_Client_Suivant_Button {
            get {
                return ResourceManager.GetString("Modifier_Client_Suivant_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove.
        /// </summary>
        internal static string Modifier_Client_Supprimer_Button {
            get {
                return ResourceManager.GetString("Modifier_Client_Supprimer_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete a room.
        /// </summary>
        internal static string Modifier_Client_Supprimer_Piece_ToolTip {
            get {
                return ResourceManager.GetString("Modifier_Client_Supprimer_Piece_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modify a customer.
        /// </summary>
        internal static string Modifier_Client_Win_Name {
            get {
                return ResourceManager.GetString("Modifier_Client_Win_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modify Delete.
        /// </summary>
        internal static string Modifier_Supprimer_Client_Sub_Menu {
            get {
                return ResourceManager.GetString("Modifier_Supprimer_Client_Sub_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choosing a photo.
        /// </summary>
        internal static string openFileDialog_Title {
            get {
                return ResourceManager.GetString("openFileDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ?.
        /// </summary>
        internal static string Question_Menu {
            get {
                return ResourceManager.GetString("Question_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à To leave.
        /// </summary>
        internal static string Quitter_Menu {
            get {
                return ResourceManager.GetString("Quitter_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à To research.
        /// </summary>
        internal static string Rechercher_Client_Rechercher_Button {
            get {
                return ResourceManager.GetString("Rechercher_Client_Rechercher_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Find a client.
        /// </summary>
        internal static string Rechercher_Client_Win_Name {
            get {
                return ResourceManager.GetString("Rechercher_Client_Win_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create a database backup.
        /// </summary>
        internal static string Sauvegarder_DB_Sub_Menu {
            get {
                return ResourceManager.GetString("Sauvegarder_DB_Sub_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choosing the backup location.
        /// </summary>
        internal static string saveFileDialog_Title {
            get {
                return ResourceManager.GetString("saveFileDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Women.
        /// </summary>
        internal static string Sexe_Femme {
            get {
                return ResourceManager.GetString("Sexe_Femme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Man.
        /// </summary>
        internal static string Sexe_Homme {
            get {
                return ResourceManager.GetString("Sexe_Homme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Work :.
        /// </summary>
        internal static string Supprimer_Travail_1st_Label {
            get {
                return ResourceManager.GetString("Supprimer_Travail_1st_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (*) Deleting a job will also delete the clients assigned to this job..
        /// </summary>
        internal static string Supprimer_Travail_2nd_Label {
            get {
                return ResourceManager.GetString("Supprimer_Travail_2nd_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove.
        /// </summary>
        internal static string Supprimer_Travail_Sub_Menu {
            get {
                return ResourceManager.GetString("Supprimer_Travail_Sub_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove.
        /// </summary>
        internal static string Supprimer_Travail_Supprimer_Button {
            get {
                return ResourceManager.GetString("Supprimer_Travail_Supprimer_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete a job.
        /// </summary>
        internal static string Supprimer_Travail_Win_Name {
            get {
                return ResourceManager.GetString("Supprimer_Travail_Win_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Work.
        /// </summary>
        internal static string Travail_Menu {
            get {
                return ResourceManager.GetString("Travail_Menu", resourceCulture);
            }
        }
    }
}
